- name: Set up the machine as root
  hosts: all_vps  
  remote_user: root
  tasks:
  - name: Initialize apt
    apt:
      update_cache: true
  - name: Do the apt upgrade
    apt:
      upgrade: full
      force: true
  - name: Install all the needed packages
    apt:
      pkg: [build-essential, curl, git, libcap-dev, libssl-dev, libuv1-dev, man, pkg-config,
        pyflakes3, python-ply, rsync, scamper, traceroute, unzip]
  - name: Put .bashrc for root
    copy:
      src: bashrc-for-root
      dest: /root/.bashrc
  - name: Make user 'metrics'
    user: 
      name: metrics
      home: /home/metrics
      shell: /bin/bash
  - name: Make .ssh for metrics
    file:
      path: /home/metrics/.ssh
      group: metrics
      mode: '0700'
      owner: metrics
      state: directory
  - name: authorized_keys for metrics
    copy:
      src: ../Local/authorized_keys
      dest: /home/metrics/.ssh/authorized_keys
      group: metrics
      mode: '0600'
      owner: metrics
- name: Set up metrics user
  hosts: all_vps
  remote_user: metrics
  tasks:
  - name: Put .bashrc for metrics
    template:
      src: bashrc-for-metrics
      dest: /home/metrics/.bashrc
  - name: make Source/
    file:
      path: /home/metrics/Source
      mode: '0700'
      state: directory
  - name: make Target/
    file:
      path: /home/metrics/Target
      mode: '0700'
      state: directory
  - name: Copy local BIND tarball and expand it
    unarchive: 
      src: bind-9.16.0.tar.xz
      dest: /home/metrics/Source,
      creates: /home/metrics/Source/bind-9.16.0
  - name: Make BIND
    shell:
      chdir: /home/metrics/Source/bind-9.16.0
      cmd: "./configure --prefix=/home/metrics/Target; make install"
      creates: /home/metrics/Target/bin/dig
  - name: Clone the repo
    git:
      repo: 'https://github.com/paulehoffman/early-metrics.git'
      dest: /home/metrics/repo
