- name: Set up the machine as root
  hosts: c00.mtric.net  
  remote_user: root
  tasks:
  - name: Initialize apt
    apt:
      update_cache: true
  - name: Do the apt upgrade
    apt:
      upgrade: full
      force: true
  - name: Install all the needed packages
    apt:
      pkg: [build-essential, curl, git, man, postgresql, pyflakes3, python-psycopg2, rsync, unzip]
  - name: Put .bashrc for root
    copy:
      src: bashrc-for-root
      dest: /root/.bashrc
  - name: Make user 'metrics'
    user: 
      name: metrics
      home: /home/metrics
      shell: /bin/bash
  - name: Make .ssh for metrics
    file:
      path: /home/metrics/.ssh
      group: metrics
      mode: '0700'
      owner: metrics
      state: directory
  - name: authorized_keys for metrics
    copy:
      src: ../Local/authorized_keys
      dest: /home/metrics/.ssh/authorized_keys
      group: metrics
      mode: '0600'
      owner: metrics
  - name: Put .bashrc for metrics
    become_user: metrics
    become: true
    template:
      src: bashrc-for-metrics
      dest: /home/metrics/.bashrc
  - name: Initialize Postgres
    become_user: postgres
    become: true
    postgresql_user:
      name: metrics
      role_attr_flags: CREATEDB,NOSUPERUSER
  