- name: Set up the machine as root
  hosts: c00.mtric.net  
  remote_user: root
  tasks:
  - name: Initialize apt
    apt:
      update_cache: true
  - name: Do the apt upgrade
    apt:
      upgrade: full
      force: true
  - name: Install all the needed packages
    apt:
      pkg: [build-essential, curl, git, man, postgresql, pyflakes3, python-psycopg2, rsync, unzip]
  - name: Put .bashrc for root
    copy:
      src: bashrc-for-root
      dest: /root/.bashrc
  - name: Make user 'metrics'
    user: 
      name: metrics
      home: /home/metrics
      shell: /bin/bash
  - name: Make .ssh for metrics
    file:
      path: /home/metrics/.ssh
      group: metrics
      mode: '0700'
      owner: metrics
      state: directory
  - name: authorized_keys for metrics
    copy:
      src: ../Local/metrics_authorized_keys
      dest: /home/metrics/.ssh/authorized_keys
      group: metrics
      mode: u+rw
      owner: metrics
  - name: Put .bashrc for metrics
    become_user: metrics
    become: true
    template:
      src: bashrc-for-metrics
      dest: /home/metrics/.bashrc
  - name: Make user 'reading'
    user: 
      name: reading
      home: /home/reading
      shell: /bin/bash
  - name: Make .ssh for reading
    file:
      path: /home/reading/.ssh
      group: reading
      mode: u+rwx
      owner: reading
      state: directory
  - name: authorized_keys for reading
    copy:
      src: ../Local/reading_authorized_keys
      dest: /home/reading/.ssh/authorized_keys
      group: reading
      mode: u+rw
      owner: reading
  - name: just-rsync.py for reading
    copy:
      src: just-rsync.py
      dest: /home/reading
      group: reading
      mode: u+rwx
      owner: reading
  - name: Initialize Postgres for metrics
    become_user: postgres
    become: true
    postgresql_user:
      name: metrics
      role_attr_flags: CREATEDB,NOSUPERUSER
- name: Install things as metrics
  hosts: c00.mtric.net  
  remote_user: metrics
  tasks:
  - name: Create first database
    postgresql_db:
      login_user: metrics
      name: metrics
  - name: Create first table
    postgresql_table:
      login_user: metrics
      db: metrics
      name: first_table
      columns:
        - id bigserial primary key
        - things text

      
