- name: Set up the machine as root
  hosts: c00.mtric.net  
  remote_user: root
  tasks:
  - name: Initialize apt
    apt:
      update_cache: true
  - name: Do the apt upgrade
    apt:
      upgrade: full
      force: true
  - name: Install all the needed packages
    apt:
      pkg: [build-essential, curl, git, man, postgresql, pyflakes3, python-psycopg2, rsync, unzip]
  - name: Put .bashrc for root
    copy:
      src: bashrc-for-root
      dest: /root/.bashrc
  - name: Make user 'metrics'
    user: 
      name: metrics
      home: /home/metrics
      shell: /bin/bash
  - name: Make .ssh for metrics
    file:
      path: /home/metrics/.ssh
      owner: metrics
      group: metrics
      mode: '0700'
      state: directory
  - name: authorized_keys for metrics
    copy:
      src: ../Local/metrics_authorized_keys
      dest: /home/metrics/.ssh/authorized_keys
      owner: metrics
      group: metrics
      mode: u+rw
  - name: Put .bashrc for metrics
    become_user: metrics
    become: true
    template:
      src: bashrc-for-metrics
      dest: /home/metrics/.bashrc
  - name: Make /sftp for transfers
    file:
      path: /sftp
      state: directory
      mode: go-w
  - name: Replace sshd_config
    copy:
      src: sshd_config-for-collector
      dest: /etc/ssh/sshd_config
  - name: Restart sshd after changing the config
    systemd:
      state: restarted
      name: sshd.service
      daemon_reload: yes      
  - name: Make user 'transfer'
    user: 
      name: transfer
      home: /home/transfer
      shell: /usr/sbin/nologin
  - name: Make .ssh for transfer
    file:
      path: /home/transfer/.ssh
      owner: transfer
      group: transfer
      mode: '0700'
      state: directory
  - name: Copy SSH public key for transfer
    copy:
      src: ../Local/transfer_rsa.pub
      dest: /home/transfer/.ssh/id_rsa.pub
      owner: transfer
      group: transfer
      mode: u+rw
  - name: Copy SSH private key for transfer
    copy:
      src: ../Local/transfer_rsa
      dest: /home/transfer/.ssh/id_rsa
      owner: transfer
      group: transfer
      mode: u+rw
  - name: Create download folder for transfer
    file:
      path: /sftp/transfer
      owner: transfer
      group: transfer
      state: directory      
  - name: Initialize Postgres for metrics
    become_user: postgres
    become: true
    postgresql_user:
      name: metrics
      role_attr_flags: CREATEDB,NOSUPERUSER
- name: Install things as metrics
  hosts: c00.mtric.net  
  remote_user: metrics
  tasks:
  - name: Create first database
    postgresql_db:
      login_user: metrics
      name: metrics
  - name: Create first table
    postgresql_table:
      login_user: metrics
      db: metrics
      name: first_table
      columns:
        - id bigserial primary key
        - things text

      
