- name: Set up the machine as root
  hosts: c00.mtric.net  
  remote_user: "{{ superuser }}"
  tasks:
  - name: Initialize apt
    apt:
      update_cache: true
  - name: Do the apt upgrade
    apt:
      upgrade: full
      force: true
  - name: Install all the needed packages
    apt:
      pkg: [build-essential, curl, git, man, postgresql, pyflakes3, python-psycopg2, rsync, unzip]
  - name: Put .bashrc for root
    copy:
      src: bashrc-for-root
      dest: /root/.bashrc
  - name: Make /sftp for transfer user
    file:
      path: /sftp
      state: directory
      mode: go-w
  - name: Replace sshd_config
    copy:
      src: sshd_config-shorter
      dest: /etc/ssh/sshd_config
  - name: Restart sshd after changing the config
    systemd:
      state: restarted
      name: sshd.service
      daemon_reload: yes      
  - name: Make user 'transfer'
    user:
      name: transfer
      home: /sftp/transfer
      shell: /bin/bash
  - name: Make user 'metrics'
    user: 
      name: metrics
      home: /home/metrics
      shell: /bin/bash
  - name: Initialize Postgres for metrics
    become_user: postgres
    become: true
    postgresql_user:
      name: metrics
      role_attr_flags: CREATEDB,NOSUPERUSER
- name: Set up transfer user
  hosts: new_vps
  remote_user: "{{ superuser }}"
  become_user: transfer
  become: yes
  tasks:
  - name: Set up authorized_keys for transfer
    authorized_key:
      user: transfer
      key: '{{lookup("file", "../Local/transfer-id_rsa.pub") }}'
  - name: Create Output/
    file:
      path: /sftp/transfer/Output
      mode: go+w
      state: directory
- name: Install things as metrics
  hosts: c00.mtric.net  
  remote_user: "{{ superuser }}"
  become: true
  become_user: metrics
  tasks:
  - name: Put .bashrc for metrics
    template:
      src: bashrc-for-metrics
      dest: /home/metrics/.bashrc
  - name: Create first database
    postgresql_db:
      login_user: metrics
      name: metrics
  - name: Create first table
    postgresql_table:
      login_user: metrics
      db: metrics
      name: first_table
      columns:
        - id bigserial primary key
        - things text

      
