- name: Freshen GitHub for metrics user in VPs
  hosts: new_vps
  remote_user: "{{ superuser }}"
  become_user: metrics
  become: yes
  tasks:
  - name: Clone the repo
    git:
      repo: 'https://github.com/paulehoffman/early-metrics.git'
      dest: /home/metrics/repo
