- name: Set up the machine as root
  hosts: new_vps  
  remote_user: "{{ superuser }}"
  tasks:
  - name: Initialize apt
    apt:
      update_cache: true
  - name: Do the apt upgrade
    apt:
      upgrade: full
      force: true
  - name: Install all the needed packages
    apt:
      pkg: [build-essential, curl, git, libcap-dev, libssl-dev, libuv1-dev, man, pkg-config,
        pyflakes3, python-ply, rsync, scamper, traceroute, unzip]
  - name: Put .bashrc for root
    copy:
      src: bashrc-for-root
      dest: /root/.bashrc
  - name: Make /sftp for transfer user
    file:
      path: /sftp
      state: directory
      mode: go-w
  - name: Replace sshd_config
    copy:
      src: sshd_config-shorter
      dest: /etc/ssh/sshd_config
  - name: Restart sshd after changing the config
    systemd:
      state: restarted
      name: sshd.service
      daemon_reload: yes      
  - name: Make user 'transfer'
    user:
      name: transfer
      home: /sftp/transfer
      shell: /bin/bash
  - name: Make user 'metrics'
    user:
      name: metrics
      home: /home/metrics
      shell: /bin/bash
- name: Set up transfer user
  hosts: new_vps
  remote_user: "{{ superuser }}"
  become_user: transfer
  become: yes
  tasks:
  - name: Set up authorized_keys for transfer
    authorized_key:
      user: transfer
      key: "{{ lookup('file', '../Local/transfer-id_rsa.pub') }}"
  - name: Create Output/
    file:
      path: /sftp/transfer/Output
      mode: go+w
      state: directory
  - name: Put the known_hosts for c00 on transfer
    known_hosts:
      name: c00.mtric.net
      key: '{{ lookup("file", "../Local/key-for-c00.txt") }}'
- name: Set up metrics user
  hosts: new_vps
  remote_user: "{{ superuser }}"
  become_user: metrics
  become: yes
  tasks:
  - name: Put .bashrc for metrics
    copy:
      src: bashrc-for-metrics
      dest: /home/metrics/.bashrc
  - name: Put short-host-name.txt
    template:
      src: short-host-name.txt
      dest: /home/metrics/short-host-name.txt
  - name: make Source/
    file:
      path: /home/metrics/Source
      mode: u+wrx,go+rx
      state: directory
  - name: make Logs/
    file:
      path: /home/metrics/Logs
      mode: u+wrx,go+rx
      state: directory
  - name: make Target/
    file:
      path: /home/metrics/Target
      mode: u+wrx,go+rx
      state: directory
  - name: Put local BIND tarball and expand it
    unarchive: 
      src: bind-9.16.0.tar.xz
      dest: /home/metrics/Source
      creates: /home/metrics/Source/bind-9.16.0
  - name: Make BIND
    shell:
      chdir: /home/metrics/Source/bind-9.16.0
      cmd: "./configure --prefix=/home/metrics/Target; make install"
      creates: /home/metrics/Target/bin/dig
  - name: Pull or freshen the Github repo
  - name: Clone the repo
    git:
      repo: 'https://github.com/paulehoffman/early-metrics.git'
      dest: /home/metrics/repo
  - name: Give the first crontab entry
    cron:   # [mba] [wca]
      name: Get measurements
      minute: "0-59/5"
      job: "/home/metrics/repo/vantage_point_metrics.py >>/home/metrics/Logs/cron-alert.txt 2>&1"
